config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root "resources#index"

  # Authentication
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # Registration
  get "/signup", to: "registrations#new"
  post "/signup", to: "registrations#create"

  # User profile and activities
  resources :users, only: [ :index, :edit, :update ] do
    collection do
      get "search"
    end
    member do
      get "my_loans"
      get "my_fines"
    end
  end


  resources :resources do
    collection do
      get "search"
    end
  end

  resources :reservations, only: [ :index, :create ] do
    member do
      patch "approve"
      patch "reject"
    end
  end

  resources :loans do
    member do
      patch "return"
      patch "close"
    end
    collection do
      get "overdue"
      get "outstanding"
      get "past"
    end
  end

  resources :fines, only: [ :index, :show ] do
    member do
      patch "pay"
      patch "collect"
    end
  end


  namespace :api do
    namespace :v1 do
      resources :resources, only: [ :index, :show ] do
        collection do
          get "search"
        end
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library Management System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">


  </head>

  <body>
    <header class="main-header">
      <div class="container">
        <div class="header-content">
          <div class="logo">
            <%= link_to 'Library System', root_path %>
          </div>
          
          <nav class="main-nav">
            <%= link_to 'Resources', resources_path %>
            <% if logged_in? %>
              <% if current_user.library_personnel? %>
                <%= link_to 'Manage Users', users_path %>
                <%= link_to 'Manage Loans', loans_path %>
                <%= link_to 'Reservations', reservations_path %>
                <%= link_to 'My Fines', fines_path %>
              <% else %>
                <%= link_to 'My Loans', loans_path %>
                <%= link_to 'My Reservations', reservations_path %>
                <%= link_to 'My Fines', fines_path %>
              <% end %>
            <% end %>
          </nav>

          <div class="user-nav">
            <% if logged_in? %>
              <span class="user-info">
      Logged as <%= current_user.library_personnel? ? 'personnel' : 'user' %>: 
      <%= link_to current_user.full_name, edit_user_path(current_user) %>  
    </span>
              <%= button_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
            <% else %>
              <span class="user-info">Not logged in</span>
              <%= link_to 'Login', login_path, class: 'nav-link' %>
              <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
            <% end %>
          </div>
        </div>
      </div>
    </header>

   <main class="container">
  <% flash.each do |name, msg| %>
    <% bootstrap_class = case name.to_sym
                         when :notice then 'success'   
                         when :alert then 'danger'    
                         else 'info'                    
                         end %>

    <%= content_tag :div, msg, class: "alert alert-#{bootstrap_class}" %>
  <% end %>

  <%= yield %>
</main>
  </body>
</html>